export const listings = {
  listing1: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 8, bedroomCount: 4, bedCount: 3, bathCount: 1 },
    sleepArrangements: {
      1: { king: 1 },
      2: { king: 1 },
      3: { king: 1 },
      4: { queen: 1 },
    },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    reviews: [
      {
        customer: 'user1',
        review:
          'Views are incredible- even better than pictured. The fire pit is gorgeous and the s’mores kits were great! This place was really beautiful and was a great spot for our wedding.',
        reviewMonth: 'September',
        reviewYear: 2021,
      },
      {
        customer: 'user2',
        review:
          'Everything about this place was awesome! The host is super responsive and responded within minutes of me asking questions. ',
        reviewMonth: 'August',
        reviewYear: 2021,
      },
      {
        customer: 'user3',
        review:
          'Absolutely spectacular! It’s even better than the pictures. Very clean as well.',
        reviewMonth: 'July',
        reviewYear: 2021,
      },
    ],
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      { name: 'Blender', icon: 'blender' },
      { name: 'Kitchen', icon: 'kitchen' },
      { name: 'Microwave', icon: 'Microwave' },
      { name: 'wifi', icon: 'wifi' },
      { name: 'Laundry', icon: 'local_laundry_service' },
      { name: 'Pets allowed', icon: 'pets' },
      { name: 'Yard', icon: 'Yard' },
      { name: 'Fireplace', icon: 'Fireplace' },
      { name: 'TV', icon: 'TV' },
      { name: 'Iron', icon: 'Iron' },
      { name: 'Balcony', icon: 'Balcony' },
      { name: 'Fire Extinguisher', icon: 'fire_extinguisher' },
      { name: 'Hangers', icon: 'checkroom' },
      { name: 'Silverware', icon: 'flatware' },
    ],
  },
  listing2: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
  listing3: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
  listing4: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
  listing5: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
  listing6: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
  listing7: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
  listing8: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
  listing9: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
  listing10: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
  listing11: {
    location: {
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      closestPark: 'Millenium Park',
      placeName: 'Crazy Boho Lake House',
      stayType: 'home',
      freeCancellation: true,
      wifi: true,
      selfCheckin: true,
      aboutLocation: `The Teton Timber House is a modern, western-style lodge, perfect for family vacations and group retreats. It's conveniently located off Ski Hill Road, minutes from Driggs and a short drive to Grand Targhee Resort. It sits on 2.2 acres with privacy from all sides and is architecturally designed to absorb maximum natural light with many large windows and skylights throughout the house. Please notify your host of any pets that will be joining.`,
    },
    images: [
      'https://bit.ly/3Enkvla',
      'https://bit.ly/3V97CBe',
      'https://bit.ly/3ylJVM6',
      'https://bit.ly/3EiuEzw',
      'https://bit.ly/3rzOdvu',
      'https://bit.ly/3SQ4CaS',
      'https://bit.ly/3V6PVC7',
      'https://bit.ly/3CDOMuN',
    ],
    cost: { USDperNight: 100, cleaningFee: 20, serviceFee: 20, minNights: 3 },
    capacity: { guestCapacity: 4, bedroomCount: 1, bedCount: 2, bathCount: 1 },
    feedbackScore: { rating: 4.85, reviewCount: 82 },
    host: {
      hostName: 'Karina',
      joinMonth: 'August',
      joinYear: 2021,
      bio: 'I have lived in Chicago all my life. Ask me anything!',
      userID: 'nanoid it upon registration',
      pic: 'https://bit.ly/3SMCMww',
    },
    amenities: [
      'hair dryer',
      'air conditioning',
      'exercise equipment',
      'fire extinguisher',
      'bbq grill',
      'pets allowed',
    ],
  },
};

export const users = {
  user1: {
    user: {
      userName: 'Annie1',
      host: true,
      joined: 2016,
      identity: true,
      phoneNumber: true,
      workEmail: true,
      bio: 'I am a foodie who loves to travel',
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      profilePicture: 'https://i.imgur.com/vHD3B2Q.png',
    },
    reviews: {
      given: [
        { month: 'May', year: 2020, wrote: 'Was a great stay!' },
        { month: 'June', year: 2020, wrote: 'Highly recommend' },
      ],
      received: [
        { month: 'July', year: 2022, wrote: 'Annie was a great guest' },
        { month: 'August', year: 2021, wrote: 'Annie was an amazing guest' },
      ],
    },
    listings: ['listing1', 'listing2', 'listing3'],
  },
  user2: {
    user: {
      userName: 'Annie2',
      host: true,
      joined: 2016,
      identity: true,
      phoneNumber: true,
      workEmail: true,
      bio: 'I am a foodie who loves to travel',
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      profilePicture: 'https://i.imgur.com/vHD3B2Q.png',
    },
    reviews: {
      given: [
        { month: 'May', year: 2020, wrote: 'Was a great stay!' },
        { month: 'June', year: 2020, wrote: 'Highly recommend' },
      ],
      received: [
        { month: 'July', year: 2022, wrote: 'Annie was a great guest' },
        { month: 'August', year: 2021, wrote: 'Annie was an amazing guest' },
      ],
    },
    listings: ['listing1', 'listing2', 'listing3'],
  },
  user3: {
    user: {
      userName: 'Annie3',
      host: true,
      joined: 2016,
      identity: true,
      phoneNumber: true,
      workEmail: true,
      bio: 'I am a foodie who loves to travel',
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      profilePicture: 'https://i.imgur.com/vHD3B2Q.png',
    },
    reviews: {
      given: [
        { month: 'May', year: 2020, wrote: 'Was a great stay!' },
        { month: 'June', year: 2020, wrote: 'Highly recommend' },
      ],
      received: [
        { month: 'July', year: 2022, wrote: 'Annie was a great guest' },
        { month: 'August', year: 2021, wrote: 'Annie was an amazing guest' },
      ],
    },
    listings: ['listing1', 'listing2', 'listing3'],
  },
  user4: {
    user: {
      userName: 'Annie',
      host: true,
      joined: 2016,
      identity: true,
      phoneNumber: true,
      workEmail: true,
      bio: 'I am a foodie who loves to travel',
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      profilePicture: 'https://i.imgur.com/vHD3B2Q.png',
    },
    reviews: {
      given: [
        { month: 'May', year: 2020, wrote: 'Was a great stay!' },
        { month: 'June', year: 2020, wrote: 'Highly recommend' },
      ],
      received: [
        { month: 'July', year: 2022, wrote: 'Annie was a great guest' },
        { month: 'August', year: 2021, wrote: 'Annie was an amazing guest' },
      ],
    },
    listings: ['listing1', 'listing2', 'listing3'],
  },
};

export const scrollBarOptions = [
  { name: 'Accessible', icon: 'Accessible' },
  { name: 'Bakery', icon: 'bakery_dining' },
  { name: 'Basketball', icon: 'sports_basketball' },
  { name: 'Bars', icon: 'Liquor' },
  { name: 'Beach', icon: 'beach_access' },
  { name: 'Biking', icon: 'pedal_bike' },
  { name: 'Bungalow', icon: 'Bungalow' },
  { name: 'Cabin', icon: 'Cabin' },
  { name: 'Camping', icon: 'Camping' },
  { name: 'Casino', icon: 'Casino' },
  { name: 'Chalet', icon: 'Chalet' },
  { name: 'Cottage', icon: 'Cottage' },
  { name: 'Icecream', icon: 'Icecream' },
  { name: 'Festival', icon: 'Festival' },
  { name: 'Fishing', icon: 'Phishing' },
  { name: 'Games', icon: 'sports_esports' },
  { name: 'Golf', icon: 'golf_course' },
  { name: 'Gym', icon: 'fitness_center' },
  { name: 'Hiking', icon: 'Hiking' },
  { name: 'Kayaking', icon: 'Kayaking' },
  { name: 'Paragliding', icon: 'Paragliding' },
  { name: 'Pool', icon: 'Pool' },
  { name: 'Sledding', icon: 'Sledding' },
  { name: 'Skating', icon: 'Roller_Skating' },
  { name: 'Smokeless', icon: 'smoke_free' },
  { name: 'Snowboarding', icon: 'Snowboarding' },
  { name: 'Solar', icon: 'solar_power' },
  { name: 'Surfing', icon: 'Surfing' },
  { name: 'Tennis', icon: 'sports_tennis' },
  { name: 'Village', icon: 'holiday_village' },
  { name: 'Tapas', icon: 'Tapas' },
  { name: 'Yoga', icon: 'self_improvement' },
];
